name: Build and Release .exe

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags, e.g., v1.0, v1.1

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install pyinstaller

      # Step 4: Build the executable (Ensure the path is correct)
      - name: Build .exe
        run: |
          pyinstaller --onefile main.py
        # If `main.py` is in the root, you can comment out or remove the `working-directory` line:
        # working-directory: src  # Update if `main.py` is in a different folder

      # Step 5: Create Release (if not exists)
      - name: Create Release (if not exists)
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      # Step 6: Upload the built executable
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/main.exe
          asset_name: main.exe
          asset_content_type: application/octet-stream
